Fixed detection of pressed key.

diff --git a/bin/backlight_off b/bin/backlight_off
--- a/bin/backlight_off
+++ b/bin/backlight_off
@@ -5,8 +5,8 @@ fuse=60
 while xinput query-state "$XINPUT_DEVICE_NAME" | fgrep -q '=down'; do
 	fuse=$((fuse-1))
 	if [ "$fuse" -le 0 ]; then
-		xinput query-state "$XINPUT_DEVICE_NAME" | fgrep '=down' | sed 's/^ *key\[\([0-9]*\)\]=down/\1/' | while read keycode; do
-			echo "Key $keycode is still pressed, cannot backlight." >&@
+		xinput query-state "$XINPUT_DEVICE_NAME" | fgrep '=down' | sed 's/^[ \t]*key\[\([0-9]*\)\]=down/\1/' | while read keycode; do
+			echo "Key $keycode is still pressed, cannot backlight." >&2
 			xmodmap -pk | grep "^ $keycode " >&2
 		done
 		break
