notification: storing some last messages in history log.

diff --git a/bin/notification b/bin/notification
--- a/bin/notification
+++ b/bin/notification
@@ -1,15 +1,29 @@
 #!/bin/bash
+MESSAGES_TO_STORE=20 # To store in message log.
+MESSAGE_LOG_FILE=/tmp/notification.log
 TITLE=notification
 ICON=
 
 usage() {
-	echo "Usage: $(basename ${0}) [-t title] [-i icon] <text>"
-	echo "  Displays notification pop-up, plays signal sound and reads message aloud"
+	echo "Usage:"
+	echo "  $(basename ${0}) [-t title] [-i icon] <text>"
+	echo "      Displays notification pop-up, plays signal sound and reads message aloud."
+	echo "      Also stores last $MESSAGES_TO_STORE messages in log."
+	echo "  $(basename ${0}) -l"
+	echo "      Prints previous $MESSAGES_TO_STORE messages."
+	echo "  $(basename ${0}) -h"
+	echo "      Prints this message and exits."
 }
 
-while getopts ":ht:i:" opt; do
+if [ "$*" == "-l" ]; then
+	cat "$MESSAGE_LOG_FILE"
+	exit 0
+fi
+
+while getopts ":ht:i:l" opt; do
 	case "$opt" in
-		h) usage; exit 1;;
+		h) usage; exit 0;;
+		l) echo "ERROR: Option -l cannot be used with other options." >&2; usage >&2; exit 1;;
 		t) TITLE=$OPTARG;;
 		i) ICON=$OPTARG;;
 		\?) echo "Invalid option -$OPTARG"; exit 1;;
@@ -22,5 +36,8 @@ play_signal &
 if [ -n "$1" ]; then
 	notify-send "$TITLE" "$@" --icon="$ICON" &
 	text-to-speech "$@" &
+	TEMPFILE="$(mktemp)"
+	echo "$(date) <${TITLE}> $@" >>"$MESSAGE_LOG_FILE"
+	tail -n "$MESSAGES_TO_STORE" "$MESSAGE_LOG_FILE" >"$TEMPFILE" && mv -f "$TEMPFILE" "$MESSAGE_LOG_FILE"
 fi
 
